# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "puppet", "6.13.0"
gem "puppet-lint"
gem "puppet-syntax"
gem "puppetlabs_spec_helper"
gem "rspec-puppet"
gem "rspec-puppet-facts"
