#!${pkgs.bash}/bin/bash

graphical_env=$(loginctl show-session $(awk '/tty/ {print $1}' <(loginctl)) -p Type | awk -F= '{print $2}')

if [ "$graphical_env" == "wayland" ] ; then
    menu_provider='bemenu -bl7'
else
    menu_provider='rofi -dmenu'
fi

menu_items=(
    "firefox -P home"
    "firefox -P work"
    "chromium"
    "firewarden chromium"
    "| xclip -selection c"
    "| wl-copy"
    "temp_firefox"
)

menu=$(printf '%s\n' "${menu_items[@]}" | $menu_provider -p browser)

if [[ $menu == \|* ]]; then
    eval echo \"$@\" $menu > /dev/null 2>&1 &
else
    eval $menu \"$@\" > /dev/null 2>&1 &
fi
